accounts:
  - accessKeyId: AKIAJU4GS5YEWF4DJITA
    secretAccessKey: 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
    bucket: wsqa-cloudtrail
    events:
     - name: RunInstances
       tags: [Owner]
     - name: SecurityGradw
       tags: [test]
    regions:
      - eu-west-1